# Generated by Django 5.0 on 2023-12-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='publicacao',
            name='video',
        ),
        migrations.AlterField(
            model_name='comunidade',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comunidade',
            name='icone_comunidade',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='icone_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='texto',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
